services:
  - type: web
    name: smart-bite
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
